version: '3'

services:
  flask_app:
    build:
      context: .  # Path to the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile for the Flask app
    expose:
      - "5000"  # Expose port 5000 to other containers

  nginx:
    image: nginx:alpine  # Use the official Nginx image
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx config
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the container
    depends_on:
      - flask_app  # Ensure Flask app starts before Nginx

#docker-compose up --build